############################################
### 🔹 TESTS POUR MENU (menu_items)
############################################

### ➤ GET tous les plats
GET http://localhost:8000/menu


### ➤ POST Pizza Margherita
POST http://localhost:8000/menu
Content-Type: application/json

{
  "name": "Pizza Margherita",
  "price": 45.0,
  "description": "Classique italienne",
  "image_url": "https://exemple.com/pizza.jpg"
}

### ➤ POST Coca Cola
POST http://localhost:8000/menu
Content-Type: application/json

{
  "name": "Coca cola",
  "price": 15.0,
  "description": "Coke",
  "image_url": "https://exemple.com/coca.jpg"
}


### ➤ PUT Mettre à jour un plat (ex: id=2)
PUT http://localhost:8000/menu/2
Content-Type: application/json

{
  "price": 50.0,
  "description": "Prix et description mis à jour"
}


### ➤ DELETE un plat par ID
DELETE http://localhost:8000/menu/1



############################################
### 🔹 TESTS POUR EMPLOYES (employees)
############################################

### ➤ GET tous les employés
GET http://localhost:8000/employees


### ➤ POST Sami Chef
POST http://localhost:8000/employees
Content-Type: application/json

{
  "full_name": "Sami Chef",
  "role": "Chef",
  "phone": "0600000000",
  "email": "sami@restaurant.com"
}

### ➤ POST Chef2
POST http://localhost:8000/employees
Content-Type: application/json

{
  "full_name": "chef",
  "role": "Chef",
  "phone": "0660000000",
  "email": "chef2@restaurant.com"
}

#




### ➤ PUT Mettre à jour un employé (ex: id=16)
PUT http://localhost:8000/employees/16
Content-Type: application/json

{
  "role": "Sous-chef",
  "phone": "0611111111"
}


### ➤ DELETE un employé par ID
DELETE http://localhost:8000/employees/13
